#!/usr/bin/env bash
#
# Cross-kernel CO-RE portability check.
#
# CO-RE resolves struct field offsets at LOAD time, against the running
# kernel's own BTF -- bpftool-generated vmlinux.h carries
# `#pragma clang attribute push (__attribute__((preserve_access_index)))`, so
# every direct field access in the BPF sources emits a relocation record rather
# than a baked-in offset. An object built against one kernel's types is
# therefore expected to load on another.
#
# "Expected to" is not "verified", and shipping prebuilt objects rests entirely
# on this holding, so this script makes the check reproducible instead of a
# one-off somebody did by hand once.
#
# Two phases, separate because they necessarily run on different kernels:
#
#   freeze   on the BUILD kernel: copy the objects aside and record their
#            digests together with the kernel they were compiled against
#   verify   on the TARGET kernel: prove the bytes are unchanged, then push
#            them through that kernel's verifier
#
# How the frozen directory travels between the two is the operator's business
# -- reboot into another kernel, copy it to another machine, boot a VM. This
# script knows nothing about hosts or transports on purpose: baking in a
# transport would bake in an environment, and this has to work for whatever
# kernel pair someone needs to check.
#
#   infra/kernel/core-portability.sh freeze
#   <get to the other kernel>
#   infra/kernel/core-portability.sh verify
#
set -euo pipefail

REPOSITORY_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
FROZEN_DIR=${SKYLINE_FROZEN_DIR:-$REPOSITORY_ROOT/build/core-portability}
OBJECTS_DIR=${SKYLINE_BPF_DIR:-$REPOSITORY_ROOT/build/bpf}
MANIFEST_NAME=manifest.env
DIGESTS_NAME=objects.sha256

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

find_speederd() {
    if [ -n "${SKYLINE_SPEEDERD:-}" ]; then
        printf '%s' "$SKYLINE_SPEEDERD"
        return
    fi
    for candidate in \
        "$REPOSITORY_ROOT/target/release/skyline-speederd" \
        "$REPOSITORY_ROOT/target/debug/skyline-speederd" \
        /usr/local/sbin/skyline-speederd
    do
        [ -x "$candidate" ] && { printf '%s' "$candidate"; return; }
    done
    printf ''
}

phase_freeze() {
    [ -d "$OBJECTS_DIR" ] || die "no objects at $OBJECTS_DIR (run 'make bpf' first)"
    # shellcheck disable=SC2312  # the glob is checked on the next line
    set -- "$OBJECTS_DIR"/*.bpf.o
    [ -e "$1" ] || die "no *.bpf.o below $OBJECTS_DIR"

    rm -rf -- "$FROZEN_DIR"
    mkdir -p -- "$FROZEN_DIR/bpf"
    cp -- "$@" "$FROZEN_DIR/bpf/"

    # Relative paths in the digest file so `sha256sum -c` works from the frozen
    # directory regardless of where it ends up.
    ( cd -- "$FROZEN_DIR/bpf" && sha256sum -- *.bpf.o > "../$DIGESTS_NAME" )

    # The running kernel at freeze time is NOT necessarily where the types came
    # from: a release build compiles against a header generated elsewhere
    # (PREBUILT_VMLINUX_H). Record the header's digest so the provenance of the
    # type definitions is recoverable later, instead of being guessed from
    # whatever kernel happened to be booted.
    local header=$REPOSITORY_ROOT/bpf/include/vmlinux.h
    local header_digest=unknown
    [ -r "$header" ] && header_digest=$(sha256sum -- "$header" | cut -d' ' -f1)

    cat > "$FROZEN_DIR/$MANIFEST_NAME" <<EOF
BUILT_UNDER_KERNEL=$(uname -r)
BUILT_ON_ARCH=$(uname -m)
VMLINUX_H_SHA256=$header_digest
FROZEN_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
OBJECT_COUNT=$#
EOF

    echo "Frozen $# object(s) built under $(uname -r):"
    sed 's/^/  /' -- "$FROZEN_DIR/$DIGESTS_NAME"
    echo
    echo "Directory: $FROZEN_DIR"
    echo "Get to the target kernel, then run: $0 verify"
}

phase_verify() {
    [ -r "$FROZEN_DIR/$MANIFEST_NAME" ] || die "no frozen set at $FROZEN_DIR (run '$0 freeze' first)"
    # shellcheck disable=SC1090  # path is computed; the file is generated by phase_freeze
    . "$FROZEN_DIR/$MANIFEST_NAME"

    echo "Built under : ${BUILT_UNDER_KERNEL:-unknown} (kernel running at build time)"
    echo "vmlinux.h   : ${VMLINUX_H_SHA256:-unknown}"
    echo "Running on  : $(uname -r)"
    if [ "${BUILT_UNDER_KERNEL:-}" = "$(uname -r)" ]; then
        echo "Note: same kernel on both sides. This is the control case -- it"
        echo "      exercises the verifier but proves nothing about portability."
    fi

    # Unchanged bytes is the whole point: without this the result could just be
    # a rebuild against the current kernel, which would prove nothing.
    echo
    echo "== byte identity =="
    ( cd -- "$FROZEN_DIR/bpf" && sha256sum -c -- "../$DIGESTS_NAME" ) \
        || die "frozen objects changed since they were recorded"

    local speederd
    speederd=$(find_speederd)
    [ -n "$speederd" ] || die "no skyline-speederd binary found; set SKYLINE_SPEEDERD=<path>"

    local config=${SKYLINE_CONFIG:-$REPOSITORY_ROOT/config/speeder.toml}
    [ -r "$config" ] || die "config not readable: $config"

    # Point the daemon at the frozen objects rather than wherever the config
    # normally looks, without editing the operator's config file.
    local generated="$FROZEN_DIR/verify.toml"
    sed "s|^bpf_dir = .*|bpf_dir = \"$FROZEN_DIR/bpf\"|" -- "$config" > "$generated"

    echo
    echo "== kernel verifier on $(uname -r) =="
    echo "  binary: $speederd"
    if "$speederd" --config "$generated" --validate-only --verify-bpf > "$FROZEN_DIR/verify.log" 2>&1; then
        echo "  PASS -- objects built under ${BUILT_UNDER_KERNEL:-unknown} load on $(uname -r)"
        echo "  full output: $FROZEN_DIR/verify.log"
    else
        echo "  FAIL -- see $FROZEN_DIR/verify.log" >&2
        tail -20 -- "$FROZEN_DIR/verify.log" >&2
        exit 1
    fi
}

case "${1:-}" in
    freeze) phase_freeze ;;
    verify) phase_verify ;;
    *)
        sed -n '2,33p' -- "$0" | sed 's/^# \{0,1\}//'
        exit 2
        ;;
esac
