#!/usr/bin/env bash
#
# Generate the reference vmlinux.h that release builds compile against.
#
# Why a reference header instead of whatever kernel the builder happens to run:
# CO-RE fixes field OFFSETS at load time, but it cannot conjure a field that
# does not exist. An object compiled against a newer kernel's types can
# reference a field added after the oldest supported kernel, and then fails to
# load there. Compiling against the OLDEST supported kernel's header avoids
# that by construction -- a field present in 6.12 is still present in 6.19,
# while the reverse does not hold.
#
# Run this on a host running the oldest supported kernel (6.12 LTS). The output
# is published as a release asset and fetched by the release workflow, which is
# why the digest is printed: the workflow pins it, so a silently swapped header
# fails the build instead of quietly changing what gets shipped.
#
# The header is NOT committed. bpf/include/vmlinux.h stays a build artefact
# (see CLAUDE.md), and a 2.5 MB generated header does not become source just
# because it is pinned.
#
#   infra/kernel/make-reference-vmlinux.sh [output-directory]
#
set -euo pipefail

BPFTOOL=${BPFTOOL:-bpftool}
VMLINUX_BTF=${VMLINUX_BTF:-/sys/kernel/btf/vmlinux}
OUTPUT_DIR=${1:-build/reference}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

command -v "$BPFTOOL" >/dev/null 2>&1 || die "bpftool not found; set BPFTOOL=<path>"
# Presence is not usability: Ubuntu's linux-tools wrapper is on PATH and still
# fails at run time when no binary matches uname -r. Run it.
"$BPFTOOL" version >/dev/null 2>&1 || die "$BPFTOOL is present but does not run"
[ -r "$VMLINUX_BTF" ] || die "no readable BTF at $VMLINUX_BTF"

kernel=$(uname -r)
case "$kernel" in
    6.12.*) ;;
    *)
        printf 'warning: running %s, not a 6.12 LTS kernel.\n' "$kernel" >&2
        printf 'warning: a header from a newer kernel can reference fields that\n' >&2
        printf 'warning: do not exist on 6.12, and objects built from it will\n' >&2
        printf 'warning: fail to load there. Continuing because there are valid\n' >&2
        printf 'warning: reasons to generate one from another kernel, but this\n' >&2
        printf 'warning: is almost certainly not the one you want to publish.\n' >&2
        ;;
esac

mkdir -p -- "$OUTPUT_DIR"
header="$OUTPUT_DIR/vmlinux-${kernel}.h"
"$BPFTOOL" btf dump file "$VMLINUX_BTF" format c > "$header.part"
grep -q 'preserve_access_index' "$header.part" \
    || die "generated header has no preserve_access_index pragma; without it every field access bakes in an offset and the result is not CO-RE relocatable"
mv -- "$header.part" "$header"

gzip -9 -kf -- "$header"
digest=$(sha256sum -- "$header.gz" | cut -d' ' -f1)

cat <<EOF

Reference header generated.

  kernel   : $kernel
  arch     : $(uname -m)
  header   : $header ($(wc -l < "$header") lines)
  published: $header.gz
  sha256   : $digest

Publish $header.gz as a release asset, then point the release workflow at it:

  gh release create reference-vmlinux-$kernel $header.gz \\
      --title "Reference vmlinux.h ($kernel)" --notes "Generated by \$0"

  gh variable set SKYLINE_REFERENCE_VMLINUX_URL --body "<asset download URL>"
  gh variable set SKYLINE_REFERENCE_VMLINUX_SHA256 --body "$digest"
EOF
